name: couponpro
region: nyc

services:
  - name: web
    environment_slug: python
    github:
      repo: niallclarke-spec/couponpro
      branch: main
      deploy_on_push: true
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    http_port: 8080
    run_command: python3 server.py
    routes:
      - path: /
    envs:
      - key: PORT
        value: "8080"
      - key: ADMIN_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: SPACES_REGION
        value: "lon1"
      - key: SPACES_BUCKET
        value: "couponpro-templates"
      - key: TELEGRAM_BOT_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: FUNDERPRO_PRODUCT_ID
        scope: RUN_TIME
        type: SECRET
      - key: DB_HOST
        scope: RUN_TIME
        type: SECRET
      - key: DB_PORT
        value: "25060"
      - key: DB_NAME
        value: "promostack-db"
      - key: DB_USER
        scope: RUN_TIME
        type: SECRET
      - key: DB_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: ENTRYLAB_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: FOREX_BOT_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: FOREX_CHANNEL_ID
        scope: RUN_TIME
        type: SECRET
      - key: TWELVE_DATA_API_KEY
        scope: RUN_TIME
        type: SECRET

# telegram-bot worker removed - webhook mode in server.py handles all bot traffic
# This prevents dual-process state conflicts where coupon_cache becomes inconsistent
