# Decap CMS config

backend:
  name: github
  repo: niallclarke-spec/couponpro
  branch: main
  base_url: https://couponpro-o4fjo.ondigitalocean.app
  auth_endpoint: /auth

# Where uploaded assets are written in your repo
media_folder: "assets/uploads"
public_folder: "/assets/uploads"

media_library:
  name: git

# Basic collection so the CMS UI can load.
# (You can expand/replace this with your real content model later.)
collections:
  - name: uploads
    label: Uploads
    label_singular: Upload
    description: Simple media uploads into assets/uploads
    files:
      - file: "assets/uploads/.keep"     # placeholder file so the folder exists in Git
        label: Upload Media
        name: media
        fields:
          - { label: "Upload files", name: "files", widget: "file", multiple: true, allow_multiple: true }